### ISSUE TITLE
No source code for Novatek.dll

### ISSUE THREAD

**Issue by matushorvath** [RobTrehy/NovaTrakt#3]
I am trying to debug why this software is crashing with my dashcam (VIOFO A129 Pro Duo), which I understand is not supported. I am actually a developer, looking into potentially contributing support for that camera if it's viable to implement. However, I can't see the source code for Novatek.dll in this repository, so it's not possible to analyze what it's internally doing.

Since this software is published under the GPL 3.0 license, could you please publish the source code for the Novatek.dll library if you have it available? It would be nice to be able to debug all components of this software, including the low level pieces, and it would be in line with this being an open source application.

Thank you for considering my request. I will understand if it is not possible to release sources for the DLL for legal reasons, but if I don't ask, I won't know, right? :). In that case, I would suggest updating the README.md file in the Novatek directory to clarify that there is no source available for the DLL.

**Comment by RobTrehy** [comment]
Hi,
I originally excluded it from the source code for various reasons - the main one being that I'm not a C# developer and didn't really want to share it as I wasn't sure if it was the "correct" way to do things!

I've added the VS solution in the Novatek/Class directory just now.

**Comment by matushorvath** [comment]
Thank you, that's awesome.

**Comment by matushorvath** [comment]
I created a pull request to better integrate the Novatek DLL source code in to the Novatrek.sln solution: #4
